### PR TITLE
unit testing in Photo.js

### PR DESCRIPTION
**Pull request by bhusalanil121**
Implemented unit testing in Photo.js

### CODE REVIEW

**Comment by alicechen1998** [comment]
Good work!!! do you have the link for unit test on js?

**Comment by bhusalanil121** [comment]
Youtube Link: https://www.youtube.com/watch?v=ML5egqL3YFE&ab_channel=KrisFoster

**Review by yywu123 — APPROVED** [review]

**Comment by yywu123** [comment]
Thank for sharing

**Comment by michali123** [comment]
nice work @bhusalanil121 still trying to run it on my end before merging, but I would recommend moving the test unit you did to the __tests__ folder. this is where all the test units are being made. 
thx!

**Comment by tenzin1308** [comment]
@bhusalanil121 nice work with testing, and also thanks for sharing the youtube link.

**Review by tenzin1308 — APPROVED** [review]

**Pull request merged**
