### PR TITLE
Send reminder

### PR DESCRIPTION
**Pull request by alicechen1998**
send a reminder to users

### CODE REVIEW

**Review by yywu123 — APPROVED** [review]
Good job on figure out how to send reminder to the user. 
Do it only work for pre-written email ?

**Comment by ValeryiaPilchuk** [comment]
Code looks great, did you do any testing and is there any tests you can add upload for it?

**Comment by alicechen1998** [comment]
> Good job on figure out how to send reminder to the user. Do it only work for pre-written email ?
whatever the email is store in Mongodb can receive the email

**Comment by bhusalanil121** [comment]
Good job, looks good

**Pull request merged**
