### PR TITLE
Data display

### PR DESCRIPTION
**Pull request by bhusalanil121**
This Will display the Assignment list at the side of CALENDER.

### CODE REVIEW

**Review by tenzin1308 — APPROVED** [review]
Nice job adding data from backend to the Assignment list.

**Review by tenzin1308 — APPROVED** [review]

**Comment by ValeryiaPilchuk** [comment]
Looks great! Is there a reason a start time is needed?

**Comment by yywu123** [comment]
I add the start time on the table because I see it is a attribute in the data. We can remove it if you think it is non necessary

**Review by yywu123 — APPROVED** [review]
Great job on connecting backend to the frontend

**Pull request merged**
