### PR TITLE
Unit testing

### PR DESCRIPTION
**Pull request by michali123**
Retrieving lost unit testing files

### CODE REVIEW

**Comment by yywu123** [comment]
I see here have code conflicting with 4 file that need to be fix before merge into the main

**Comment by tenzin1308** [comment]
@michali123 is the reason for you doing the rebase is because of those two files in under the __test__ folder?

**Comment by bhusalanil121** [comment]
Yes @tenzin1308, thats mainly two file conflicting with our restructured version. And these two are giving some Module not found error. I spent couple of hours to debug code, but could not solve it.  Just need to add that two file under test separately and debug code.

**Comment by michali123** [comment]
> Yes @tenzin1308, thats mainly two file conflicting with our restructured version. And these two are giving some Module not found error. I spent couple of hours to debug code, but could not solve it. Just need to add that two file under test separately and debug code.

hey @tenzin1308 , basically what Anil mentioned above,
after the reconstruction I had serious troubles with running test units with jest and react, so I ended up re-cloning the whole project from scratch and it seemed to solve thee problem.  
this branch and pull request could be ignored. 
thx!

**Pull request closed without merging**
